server:
  port: 0

spring:
  application:
    name: ms-auth

jwt:
  secret: qwertyuiop

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://locaihost:8761/eureka}
    fetch-registry: true