server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ElinaFemida/market_config/
          default-label: main
          username: elina
          password: GeekBrains123
          clone-on-start: true

#eureka:
#  client:
#    service-url:
#      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}